import type { Metadata } from "next";
import localFont from 'next/font/local';
import { Geist } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const neueBrucke = localFont({
  variable: '--font-neue-brucke',
  src: '../public/fonts/Neue-Brucke-Regular.ttf',
  display: 'auto',
})

const international = localFont({
  variable: '--font-international',
  src: '../public/fonts/NB-International.otf',
  display: 'auto',
})

const berg = localFont({
  variable: '--font-berg',
  src: '../public/fonts/Berg-Regular.ttf',
  display: 'auto',
});

const parrish = localFont({
  variable: '--font-parrish',
  src: '../public/fonts/Parrish-Roman.ttf',
  display: 'auto',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};  

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${neueBrucke.variable}
           ${international.variable} ${berg.variable} ${parrish.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
